### ISSUE TITLE
xlua编译后生成的dll与原始工程自带的dll运行结果不一致。

### ISSUE THREAD

**Issue by TestVanBake** [yasio/yasio#455]
编译环境：windows, vs2022。

xlua 工程通过 build_win64_lua53.bat生产的xlua.dll会报以下 connect lost错误，debug dll显示 error -27,"invalid packet".
![image](https://github.com/user-attachments/assets/2f13576f-c853-43d7-bd51-2e16353c4258)
修改 lenghtFieldOffset 为-1后结果与原生的一致。
![image](https://github.com/user-attachments/assets/eeae4f25-c444-453e-ac50-8458524c8ef4)

![image](https://github.com/user-attachments/assets/40159c00-746e-4d99-9544-50685d774e82)

**Comment by TestVanBake** [comment]
@halx99 ，可以参考 https://github.com/TestVanBake/xLua_yasio/actions/runs/11955477488 里 [plugin_lua53_windows]的xlua.dll，fork出来后只改了pulish.yaml的编译环境。

**Comment by halx99** [comment]
xlua 版本有点旧了，我更新下吧

**Comment by halx99** [comment]
更新好了，xlua 和 yasio 都更新到了最新，测试 OK，dll 你本地自己编译下
https://github.com/yasio/xlua

![image](https://github.com/user-attachments/assets/4a91a509-c95d-4fbe-865a-4f03c92a5007)

**Comment by TestVanBake** [comment]
@halx99   默认设置为C++ 17后  android 的luajit会编译报错，android编译luajit的ndk要求版本为r15c，比较老，怎么才能兼容下？https://github.com/TestVanBake/xLua_yasio/actions/runs/12002030635/job/33453384241
![image](https://github.com/user-attachments/assets/394ae3f8-194f-4746-a107-92635b2cf616)

**Comment by halx99** [comment]
ndk 版本相关，推荐用 ndk-r23，unity-2022 之后都是 r23

**Comment by halx99** [comment]
luajit 也可以用 ndk-r23 编译的，参考： https://github.com/simdsoft/1kiss
